import { getServerSession } from 'next-auth'
import { SessionProvider } from '../../components/SessionProvider'
import SideBar from '../../components/SideBar'
import './globals.css';
import { authOptions } from '../../pages/api/auth/[...nextauth]';
import Login from '../../components/Login';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="en">
      <head />
      <body>
        <SessionProvider session={session}>
          {!session? (
            <Login />
          ):(
            <div className='flex'>
            {/* Sidebar */}
            <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:win-w-[20rem]">
              <SideBar />
            </div>
            {/* Client Provider - Notification */}
            <div className='bg-[#343541] flex-1'>{children}</div>
          </div>
          )}
        
        </SessionProvider>
      </body>
    </html>
  )
}
